[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling configuration
[forms]
  [forms.handlers]
    [forms.handlers.email]
      to = "your-email@example.com"  # Replace with your email address
      from = "EcoSearch Waitlist <noreply@ecosearch.com>"
      subject = "New Waitlist Submission"
      template = "email-template.html" 