[build]
  publish = "/"
  skip_files = [
    "*.md",
    "*.txt",
    "*.json",
    "*.xml",
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.zip"
  ]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-form-handler"

[forms]
  [forms.waitlist]
    name = "waitlist"

[forms.waitlist.handlers.email]
  to = ["your-email@example.com"]
  from = "EcoSearch Waitlist <no-reply@netlify.com>"
  subject = "New Waitlist Submission"

[forms.waitlist.handlers.email.headers]
  X-Priority = "1"
  X-MSMail-Priority = "High"
  Importance = "high"
  Priority = "urgent"
